### ISSUE TITLE
About Kinetic dataset

### ISSUE THREAD

**Issue by JHang2020** [firework8/BRL#1]
Hi, thanks for your great work!
I was wondering if you could tell me the specific training settings of GCN on Kinect dataset, such as pipeline(transformations) and so on. I didn't find the corresponding instructions on the original pyskl repo either.

Thank you very much for your help!

**Comment by firework8** [comment]
Thank you for your interest! I was out partying with friends yesterday, so sorry I couldn't respond in time.
I have updated the training settings for the Kinect dataset and also uploaded the checkpoints and training logs. Since the original pyskl repo didn't have the GCN setup, this is what I reproduced the setup.
Hope this is helpful for you. (^_^)
